import React from 'react'
import { Badge, Container, Row,Col,Progress } from 'reactstrap'
import { makeStyles } from '@material-ui/core/styles';
import Avatar from '@material-ui/core/Avatar';


const useStyles = makeStyles((theme) => ({
    root: {
      display: 'flex',
      '& > *': {
        margin: theme.spacing(1),
      },
    },
  }));
  


 export default function ProjectDetail(props) {
    const classes = useStyles();
    return (
        <div >
        <Container width="230" height='300' color = 'primary'>
        <span><h5>dashboard <Badge color='primary'>early</Badge></h5></span>
        <span><text>A flex container is the box generated by an element with a computed display of flex</text></span>
        <Row>
        <Col><text>start date</text><h5>{new Date().toLocaleTimeString()}</h5></Col>
        <Col><text>close date</text><h5>{new Date().toLocaleTimeString()}</h5></Col>
        <Col></Col>
        </Row>
        
        <div className="text-center">20%</div>
      <Progress value="1" max="5" />
      <text> 1/5 task completed</text><br/>
      <text>assigned to </text>
      <div className={classes.root}>
    <Avatar alt="Remy Sharp" src="/static/images/avatar/1.jpg" className={classes.small} />
    <Avatar alt="Remy Sharp" src="/static/images/avatar/1.jpg" />
     <Avatar alt="Remy Sharp" src="/static/images/avatar/1.jpg" className={classes.large} />
     </div>
        </Container>
        </div>
        
    )
}
